version: '3.3'

services:
  wso2mi:
    container_name: wso2mi
    hostname: wso2mi
    image: wso2/wso2mi:4.0.0
    restart: unless-stopped
    links:
      - wso2is   
      - wso2database  
    ports:
      - 8290:8290
      - 8253:8253
      - 9164:9164
    networks:
      - dnasport
    volumes: 
      - ${WSO2_MI_CUSTOM}:/home/wso2carbon/shared
      - ${WSO2_MI_ENTRY_POINT}/wso2mi-entry-point.sh:/home/wso2carbon/wso2mi-entrypoint.sh
      - wso2mi_carbonapps:${WSO2_MI_CONTAINER_CARBONAPPS}
    entrypoint: 
      - /home/wso2carbon/wso2mi-entrypoint.sh 
    depends_on:
      - wso2database
  wso2is:
    image: wso2/wso2is:5.11.0
    container_name: wso2is
    hostname: wso2is
    restart: unless-stopped
    ports:
      - 9443:9443
    networks:
      - dnasport
    volumes: 
      - ${WSO2_IS_CUSTOM}:/home/wso2carbon/shared
      - ${WSO2_IS_ENTRY_POINT}/wso2is-entry-point.sh:/home/wso2carbon/wso2is-entrypoint.sh
      - wso2is_carbonapps:${WSO2_IS_CONTAINER_CARBONAPPS}
    entrypoint: 
      - /home/wso2carbon/wso2is-entrypoint.sh 
    depends_on:
      - wso2database
    links:
      - wso2database
  wso2database:
    image: mariadb:10.6.5
    container_name: wso2database
    hostname: wso2database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
       - "3306:3306"
    networks:
       - dnasport
    volumes:
      - mariadb_data:/var/lib/mysql
networks:
  dnasport:
    driver: bridge
volumes:
  mariadb_data:
    external: false
  wso2mi_carbonapps:
    external: false
  wso2is_carbonapps:
    external: false