create database transactiondb character set latin1;

use transactiondb;

CREATE TABLE IF NOT EXISTS CURRENT_STATS (
  TIME_STAMP DATE NOT NULL,
  NODE_ID VARCHAR(40) NOT NULL,
  TRANSACTION_COUNT INT NOT NULL,
  TRANSACTION_COUNT_ENCRYPTED VARCHAR(400) NOT NULL
) ENGINE INNODB;

